[package]
edition = "2024"
name = "perfetto-sdk-derive"
version = "0.1.2"
authors = ["David Reveman <dreveman@gmail.com>"]
description = "Procedural macros for Perfetto"
readme = "README.md"
keywords = [
    "tracing",
    "perfetto",
]
categories = ["development-tools::profiling"]
license = "Apache-2.0"
homepage = "https://www.perfetto.dev"
repository = "https://github.com/google/perfetto"

[lib]
proc-macro = true

[features]
default = ["vendored"]
vendored = ["perfetto-sdk/vendored"]

[dependencies]
perfetto-sdk = { path = "../perfetto", version = "0.1", default-features = false }
syn = { version = "2", features = ["full"] }
quote = "1.0.8"
proc-macro2 = "1.0"

[[example]]
name = "derive"
path = "examples/derive.rs"
