[package]
edition = "2024"
name = "perfetto-sdk-protos-gpu"
version = "0.1.2"
authors = ["David Reveman <dreveman@gmail.com>"]
description = "Extra protobuf bindings for GPU events"
readme = "README.md"
keywords = [
    "tracing",
    "perfetto",
]
categories = ["development-tools::profiling"]
license = "Apache-2.0"
homepage = "https://www.perfetto.dev"
repository = "https://github.com/google/perfetto"

[features]
default = ["vendored"]
vendored = ["perfetto-sdk/vendored"]

[dependencies]
perfetto-sdk = { path = "../perfetto", version = "0.1.2", default-features = false }
paste = "1"

[[example]]
name = "gpu_counters"
path = "examples/gpu_counters.rs"
